config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    post 'addresses', to: 'users/registrations#create_add'
  end


  root to: "items#index"
  resources :items do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
      get 'search_tag'
    end
  end

  resources :users, only: [:new, :show, :edit, :update, :create]


  resources :notices, only: [:index, :destroy]

  resources :rooms, only: [:create, :show, :new, :destroy] do
    resources :messages, only: :create
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :item_tag_relations
  has_many :tags, through: :item_tag_relations, dependent: :destroy
  has_many :likes
  has_many :liked_users, through: :likes, source: :user


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :season
  belongs_to_active_hash :prefecture

  def self.search(search)
    if search != ""
      Item.where('text LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, only: [:edit]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @items = Item.page(params[:page]).reverse_order
    @like = Like.new

    @item = Item.find(Like.group(:item_id).order('count(item_id) desc').limit(1).pluck(:item_id))
  end

  def new
    @item = ItemsTag.new
  end

  def create
    @item = ItemsTag.new(item_params)
    if @item.valid?
      @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    if user_signed_in? && current_user.id == @item.user_id
      @item.destroy
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
    @like = Like.new
  end

  def search
    @items = Item.search(params[:keyword])
    @item = Item.page(params[:page]).reverse_order
  end

  def search_tag
    return nil if params[:keyword] == ""
    tag = Tag.where(['name LIKE ?', "%#{params[:keyword]}%"] )
    render json:{ keyword: tag }
  end





  private
  def item_params
    params.require(:items_tag).permit(:text, :season_id, :category_id, :prefecture_id, :message, images: []).merge(user_id: current_user.id, item_id: params[:item_id], tag_id: params[:tag_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    @item = Item.find(params[:id])
    redirect_to action: :index unless user_signed_in? && current_user.id == @item.user.id
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
      <%= form_with model: @item, url: item_path, method: :patch, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <%= f.file_field :images, name: 'items_tag[images][]', id: 'item_image' %>

      <div id="image-list"></div>

      <div class="tags">
      <%= f.label :message, "タグ" %>
      <%= f.text_field :message, id: 'items_tag_message'%>
      </div>

      <div id="search-result"></div>

      <div class="weight-bold-text">
        Category
      <span class="indispensable">必須</span>
      </div>
        <%= f.collection_select :category_id, Category.all, :id, :name, {} %>


      <div class="weight-bold-text">
        Season
      <span class="indispensable">必須</span>
      </div>
        <%= f.collection_select :season_id, Season.all, :id, :name, {} %>


      <div class="weight-bold-text">
        Place
      <span class="indispensable">必須</span>
      </div>
        <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, {} %>


      <%= f.text_area :text, placeholder: "Text", rows: "10" %>


      <%= f.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="contents row">
  <div class="radius">

    <% if user_signed_in? %>
      <div class="search">
        <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form|%>
          <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      </div>
    <% end %>

    <% @items.each do |item| %>
    <div class="radius2">
      <div class="content_po">
        <p>
          <% item.images.each do |image| %>
          <%= image_tag image %>
          <% end %>
          <div class="text1">
            <h3>
              <p>投稿者
                <%= link_to item.user.nick_name, "/users/#{item.user_id}"%>
              </p>
            </h3>
            <div class="textor">
              <p>
              <%= l item.created_at, format: :short %>
              </p>
            </div>
              <%= item.text %>
          </div>
          <div class="textlike">
            <h3>
              <p>
                <span>いいね！件数：</span><%= item.liked_users.count %>
              </p>
            </h3>
          </div>
          <div class="more">
            <ul class="more_list">
            <% if user_signed_in? %>
              <li>
                <%= link_to '詳細', item_path(item.id), method: :get %>
              </li>
            <% end %>
              <% if user_signed_in? && current_user.id == item.user_id %>
              <li>
                <%= link_to '編集', edit_item_path(item.id), method: :get %>
              </li>
              <li>
                <%= link_to '削除', item_path(item.id), method: :delete %>
              </li>
              <% end %>
            </ul>
            </div>
          </div>
        </div>
      <% end %>

    <div class="iine">
      <h6>
      «いいね数 トップ (１位のみ表示)»
      </h6>
    </div>
    <% @item.each do |item|%>
    <div class="radius2">
      <div class="content_po">
        <p>
          <% item.images.each do |image| %>
          <%= image_tag image %>
          <% end %>
          <div class="text1">
            <h3>
              <p>投稿者
                <%= link_to item.user.nick_name, "/users/#{item.user_id}"%>
              </p>
            </h3>
            <div class="textor">
              <p>
              <%= l item.created_at, format: :short %>
              </p>
            </div>
              <%= item.text %>
          </div>
          <div class="textlike">
            <h3>
              <p>
                <span>いいね！件数：</span><%= item.liked_users.count %>
              </p>
            </h3>
          </div>
          <div class="more">
            <ul class="more_list">
            <% if user_signed_in? %>
              <li>
                <%= link_to '詳細', item_path(item.id), method: :get %>
              </li>
            <% end %>
              <% if user_signed_in? && current_user.id == item.user_id %>
              <li>
                <%= link_to '編集', edit_item_path(item.id), method: :get %>
              </li>
              <li>
                <%= link_to '削除', item_path(item.id), method: :delete %>
              </li>
              <% end %>
            </ul>
            </div>
          </div>
        </div>
    <% end %>
      <div class="page">
        <%= paginate @items %>
      </div>
    </p>
  </div>
</div>

app/views/items/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
      <%= form_with model: @item, url: items_path, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <%= f.file_field :images, name: 'items_tag[images][]', id: 'item_image' %>

      <div id="image-list"></div>

      <div class="tags">
      <%= f.label :message, "タグ" %>
      <%= f.text_field :message %>
      </div>

      <div id="search-result"></div>

      <div class="weight-bold-text">
        Category
      <span class="indispensable">必須</span>
      </div>
        <%= f.collection_select :category_id, Category.all, :id, :name, {} %>


      <div class="weight-bold-text">
        Season
      <span class="indispensable">必須</span>
      </div>
        <%= f.collection_select :season_id, Season.all, :id, :name, {} %>


      <div class="weight-bold-text">
        Place
      <span class="indispensable">必須</span>
      </div>
        <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, {} %>


      <%= f.text_area :text, placeholder: "Text", rows: "10" %>


      <%= f.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/items/search.html.erb
<div class="contents row">
  <div class="radius">
    <div class="search">
      <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
        <% if user_signed_in? %>
          <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      <% end %>
    </div>
    <div class="searches">
      <p>《検索結果》</p>
    </div>
    <% @items.each do |item| %>
      <div class="radius2">
        <div class="content_po">
        <p>
          <% item.images.each do |image| %>
          <%= image_tag image %>
          <% end %>
          <div class="text1">
            <h3>
              <p>投稿者
                <%= link_to item.user.nick_name, "/users/#{item.user_id}"%>
              </p>
            </h3>
              <%= item.text %>
          </div>
          <div class="textlike">
            <h3>
              <p>
                <span>いいね！件数：</span><%= item.liked_users.count %>
              </p>
            </h3>
          </div>
          <div class="more">
            <ul class="more_list">
            <% if user_signed_in? %>
              <li>
                <%= link_to '詳細', item_path(item.id), method: :get %>
              </li>
            <% end %>
              <% if user_signed_in? && current_user.id == item.user_id %>
              <li>
                <%= link_to '編集', edit_item_path(item.id), method: :get %>
              </li>
              <li>
                <%= link_to '削除', item_path(item.id), method: :delete %>
              </li>
              <% end %>
            </ul>
            </div>
          </div>
        </div>
      <% end %>
      <div class="page">
        <%= paginate @item %>
      </div>
    </p>
  </div>
</div>

app/views/items/show.html.erb
<div class="contents row">
  <div class="content_po">
    <span>
      <p></p>
    </span>
      <% @item.images.each do |image| %>
      <%= image_tag image %>
      <% end %>
        <div class="more">
          <ul class="more_list">
            <% if user_signed_in? && current_user.id == @item.user_id %>
              <li>
                <%= link_to '編集', edit_item_path(@item.id), method: :get %>
              </li>
              <li>
                <%= link_to '削除', item_path(@item.id), method: :delete %>
              </li>
            <% end %>
          </ul>
        </div>
    <div class="item-name">
    <span class="name">
      <a href="/users/<%= @item.user.id %>">
        <span>投稿者 </span><%= @item.user.nick_name %>
      </a>
    </span>
    </div>
  <div class="itemtext">
  <div class="textor">
    <p>
    <%= l @item.created_at, format: :short %>
    </p>
  </div>
    <p><%= @item.text %></p>
  </div>
  <p>季節 ”<%= @item.season.name%>”</p>
  <p>場所 ”<%= @item.prefecture.name%>”</p>
  <% if current_user.already_liked?(@item) %>
    <%= button_to 'いいね！を取り消す', item_like_path(@item), method: :delete %>
  <% else %>
    <%= button_to 'いいね！', item_likes_path(@item) %>
  <% end %>
  <div class="like3">
  <h3>いいね！件数: <%= @item.likes.count %></h3>
  </div>
  <p>いいね！したユーザー</p>
  <div class="like4">
  <% @item.liked_users.each do |user| %>
    <li><%= link_to user.nick_name, user_path(user.id), method: :get %></li>
  </div>
  <% end %>
  <div class="container">
  <% if user_signed_in? %>
    <%= form_with(model: [@item, @comment], method: :show, local: true) do |f| %>
      <div class="field">
        <%= f.label :text, "コメント" %><br />
        <%= f.text_field :text %>
      </div>
  <div class="actions">
    <%= f.submit "送信する", class: :form__btn  %>
  </div>
    <% end %>
  <% end %>
    <ul class="comments_lists">
      <li class="comments_list">
        <% if @comment %>
          <% @comments.reverse_each do |comment| %>
            <p>
              <div id='comments'>
                <strong><%= link_to comment.user.nick_name, "/users/#{comment.user_id}" %>：</strong>
                <%= comment.text %>
              </div>
            </p>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</div>